apiVersion: v1
kind: Pod
metadata:
  name: storage-hostpath
  namespace: lab
spec:
  volumes:
  - name: host-data
    hostPath:
      path: /tmp/k8s-lab-hostpath
      type: DirectoryOrCreate
  containers:
  - name: writer
    image: busybox:1.36
    command: ["sh", "-c", "while true; do date >> /host/data.log; sleep 5; done"]
    volumeMounts:
    - name: host-data
      mountPath: /host
