apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-demo
  namespace: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-demo
  template:
    metadata:
      labels:
        app: workload-demo
        version: v1
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
        env:
        - name: APP_VERSION
          value: v1
        ports:
        - containerPort: 80
