apiVersion: v1
kind: Pod
metadata:
  name: storage-emptydir
  namespace: lab
spec:
  volumes:
  - name: cache
    emptyDir: {}
  containers:
  - name: writer
    image: busybox:1.36
    command: ["sh", "-c", "while true; do date >> /cache/out.log; sleep 5; done"]
    volumeMounts:
    - name: cache
      mountPath: /cache
  - name: reader
    image: busybox:1.36
    command: ["sh", "-c", "tail -f /cache/out.log"]
    volumeMounts:
    - name: cache
      mountPath: /cache
