apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: net-demo
  namespace: lab
spec:
  ingressClassName: nginx
  rules:
  - host: net-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: net-demo
            port:
              number: 80
