apiVersion: batch/v1
kind: Job
metadata:
  name: print-time
  namespace: lab
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: writer
        image: busybox:1.36
        command: ["sh", "-c", "date; echo job-done"]
