apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-toleration-demo
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taint-toleration-demo
  template:
    metadata:
      labels:
        app: taint-toleration-demo
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: lab
        effect: NoSchedule
      containers:
      - name: app
        image: busybox:1.36
        command: ["sh", "-c", "while true; do date; sleep 30; done"]
